// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopicTalks.Infrastructure.Persistence;

#nullable disable

namespace TopicTalks.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330092822_init4")]
    partial class init4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.Answer", b =>
                {
                    b.Property<long>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AnswerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("AnswerId");

                    b.HasIndex(new[] { "ParentAnswerId" }, "IX_Answers_ParentAnswerId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_Answers_QuestionId");

                    b.HasIndex(new[] { "UserId" }, "IX_Answers_UserId");

                    b.ToTable("Answers", "post");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.Question", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QuestionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestionId");

                    b.HasIndex(new[] { "UserId" }, "IX_Questions_UserId");

                    b.ToTable("Questions", "post");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("UserRoleRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserRoleUserId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId");

                    b.HasIndex("UserRoleRoleId", "UserRoleUserId");

                    b.ToTable("Roles", "enum");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserRoleRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserRoleUserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleRoleId", "UserRoleUserId");

                    b.ToTable("Users", "auth");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.UserDetail", b =>
                {
                    b.Property<long>("UserDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserDetailsId"));

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserDetailsId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserDetails_UserId");

                    b.ToTable("UserDetails", "auth");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.UserRole", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.Answer", b =>
                {
                    b.HasOne("TopicTalks.Infrastructure.Models.User", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Answers_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.Question", b =>
                {
                    b.HasOne("TopicTalks.Infrastructure.Models.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Questions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.Role", b =>
                {
                    b.HasOne("TopicTalks.Infrastructure.Models.UserRole", null)
                        .WithMany("Role")
                        .HasForeignKey("UserRoleRoleId", "UserRoleUserId");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.User", b =>
                {
                    b.HasOne("TopicTalks.Infrastructure.Models.UserRole", null)
                        .WithMany("User")
                        .HasForeignKey("UserRoleRoleId", "UserRoleUserId");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.UserDetail", b =>
                {
                    b.HasOne("TopicTalks.Infrastructure.Models.User", "User")
                        .WithMany("UserDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UserDetails_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.UserRole", b =>
                {
                    b.HasOne("TopicTalks.Infrastructure.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopicTalks.Infrastructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.User", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Questions");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("TopicTalks.Infrastructure.Models.UserRole", b =>
                {
                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
